### ISSUE TITLE
Connector config spec contradicts Javadoc

### ISSUE THREAD

**Issue by danielkec** [eclipse/microprofile-reactive-messaging#102]
While there is `connector` described as FQN in the spec:

- `connector` attribute indicating the fully qualified name of the connector.

https://github.com/eclipse/microprofile-reactive-messaging/blame/master/spec/src/main/asciidoc/architecture.asciidoc#L1188

Javadoc says `It must match the name given to the {@link Connector} qualifier`
https://github.com/eclipse/microprofile-reactive-messaging/blob/8b5655c5622cd8dc3168a51638dd8d1566a6f593/api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/ConnectorFactory.java#L36-L46

**Comment by cescoffier** [comment]
The JavaDoc is right. The spec should be updated. 

A note should be added. While it should be a name and not FQCN, it still needs to be specific enough to avoid conflicts. Typically, in SmallRye, we prefix them with "smallrye-...".
