### ISSUE TITLE
Misleading 2.0.0-RC1 text

### ISSUE THREAD

**Issue by kabir** [eclipse/microprofile-reactive-messaging#131]
The following text given for https://github.com/eclipse/microprofile-reactive-messaging/releases/tag/2.0-RC1 seems wrong (probably copied from RSO?):

> This release only contains one change, which is to bring in Reactive Stream newly released 2.0-RC1.

**Comment by Emily-Jiang** [comment]
Fixed. Thank you @kabir for reporting this!
