### ISSUE TITLE
Jakarta EE 9.1 alignment

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-reactive-messaging#137]
### For each spec, the following updates need to happen, refer [this doc](https://docs.google.com/document/d/1bhhfmhxHJpQdmdUtQw5o_WtScpzkfHoTNGPvrQnGhc0/edit) for instructions:

- [ ] Only jakarta namespace changes are allowed in the release without any other functional changes with the exception of typos or tck fixes
- [ ] pom.xml: utilise microprofile-parent 2.4 as it has pulled in all of the Jakarta EE 9.1 as well as the necessary TCK dependencies (see [this](https://github.com/eclipse/microprofile-fault-tolerance/pull/593) PR on how to)
- [ ] spec docs: rename Java EE to Jakarta EE, rename javax to jakarta: `find . -type f -name '*.asciidoc' -exec sed -i '' s/javax./jakarta./ {} +`
- [ ] Update all javax to jakarta for all java files `import javax.*` needs to be updated to `jakarta.*`: `find . -type f -name '*.java' -exec sed -i '' s/javax./jakarta./ {} +`
- - [ ] TCKs
- - [ ] APIs
- [ ] Update bnd file:  `find . -type f -name ‘*.bnd' -exec sed -i '' s/javax./jakarta./ {} +`

- [ ] service loader file javax.* to jakarta.*: `find . -type f -name "javax*" -exec sh -c 'mv "$0" "${0/javax/jakarta}"' '{}' \;
- [ ] Perform step 4/5/6 in [this](https://docs.google.com/document/d/1bhhfmhxHJpQdmdUtQw5o_WtScpzkfHoTNGPvrQnGhc0/edit) doc
- [ ] Perform a RC release off the `master` branch

**Comment by tomas-langer** [comment]
Is anybody working on this issue? I could do the update to parent + jakarta. I would need to leave the release part to somebody else...

**Comment by Emily-Jiang** [comment]
@tomas-langer go ahead to do the PR. I can help with the review and the release part.

**Comment by danielkec** [comment]
> @tomas-langer go ahead to do the PR. I can help with the review and the release part. You can follow the steps documented in this issue and I have updated it to reflect the current status. By the way, I think you need to do [this](https://github.com/eclipse/microprofile-reactive-streams-operators/issues/169) issue first.

Operators PR prepared eclipse/microprofile-reactive-streams-operators/pull/171
