### ISSUE TITLE
DefaultOverflowStrategyOverflowTest expects downstream error

### ISSUE THREAD

**Issue by danielkec** [eclipse/microprofile-reactive-messaging#147]
Spec defines `If @OnOverflow is absent, the buffer strategy OnOverflow.Strategy.BUFFER will be used.` and `If the buffer is full, an exception will be thrown from the send method` but there is no mention about propagating the error to the downstream with error signal.

Yet [DefaultOverflowStrategyOverflowTest](https://github.com/eclipse/microprofile-reactive-messaging/blob/aff8ae8b8669fb7d02351233a6afdfe2eed0c9b9/tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/overflow/DefaultOverflowStrategyOverflowTest.java#L43-L51) expects downstream failure.

https://github.com/eclipse/microprofile-reactive-messaging/blob/aff8ae8b8669fb7d02351233a6afdfe2eed0c9b9/tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/overflow/DefaultOverflowStrategyOverflowTest.java#L43-L51

https://github.com/eclipse/microprofile-reactive-messaging/blob/aff8ae8b8669fb7d02351233a6afdfe2eed0c9b9/tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/overflow/BeanUsingDefaultOverflow.java#L104

**Comment by danielkec** [comment]
This is very confusing as TCK test `BufferOverflowStrategyOverflowTest` specifically asserts there is no downstream error:

https://github.com/eclipse/microprofile-reactive-messaging/blob/aff8ae8b8669fb7d02351233a6afdfe2eed0c9b9/tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/channel/overflow/BufferOverflowStrategyOverflowTest.java#L49-L59

And default strategy is specifically mentioned by spec 
![image](https://user-images.githubusercontent.com/1773630/162050261-61eeb248-f620-4899-ab87-bcf407d9a185.png)

**Comment by Azquelt** [comment]
I agree the test looks wrong. The `BufferOverflowStrategyOverflow` test was updated in 8b6a241 and `DefaultOverflowStrategyOverflow` should have been updated at the same time.

**Comment by tony2415** [comment]
Hi guys, I have a problem with bufferoverflow in quarkus. I'm try to resolve with 
    @Incoming("leituras")
    @NonBlocking
    @OnOverflow(value = OnOverflow.Strategy.DROP, bufferSize = 1000)
    public CompletionStage<Void> consumeMessage(Message<String> message). I'm using onOverFlow, but not working. How can I resolve this problem. This application is my consumer.

**Comment by Azquelt** [comment]
@tony2415 It sounds like you're having an issue getting Quarkus to work as you want? If so, you need to raise a quarkus issue for your problem.

You would raise an issue here if you had an idea for a new API to be added to the spec, or for a problem with the Javadoc or spec text.
