### ISSUE TITLE
AsynchronousPayloadProcessorAckTest expects stream to continue after nack

### ISSUE THREAD

**Issue by danielkec** [eclipse/microprofile-reactive-messaging#148]
AsynchronousPayloadProcessorAckTest expects stream to continue deliver items after first nack. While the spec doesn't define how the processor method `CompletionStage<O> method(I payload)` should flatMap exceptionally completed CompletionStage, same behavior like `flatMapCompletionStage` should be IMHO expected and exceptionally completed CS should be mapped to rx error signal.  

https://github.com/eclipse/microprofile-reactive-messaging/blob/aff8ae8b8669fb7d02351233a6afdfe2eed0c9b9/tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/acknowledgement/AsynchronousPayloadProcessorAckTest.java#L159-L180

**Comment by danielkec** [comment]
Same goes for the `PayloadProcessorAckTest`

**Comment by cescoffier** [comment]
This was done on purpose to allow implementations to provide recovery and failure management features (DLQ and other things like this). If you send the error signals, it will automatically cancel the subscription.
