### ISSUE TITLE
Economy of properties and Connector load efficiency from PR #22

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-reactive-messaging#28]
As discussed at 
https://github.com/eclipse/microprofile-reactive-messaging/pull/22#issuecomment-493868173

I have two current concerns with the current design.

1) 
That all properties need to contain and be specific to a particular topic/que,
this means where we have a number of queues there will be a lot of properties
with duplicate info and it will be harder to spit application config and devops
config properties like kafka-credentials.  I would like it if it was possible to
have a property that applied to all streams of a particular message provider
(or perhaps ingoing or outgoing from one provider less ideally).

2)
I do not like the design of having to load Connectors that might ultimately
be unused just to call the type() method. When we have many Connectors
this will be ineffient. One idea is to bootstrap from the MessageProvider
interface, Clement has mentioned using Qualifiers.

**Comment by cescoffier** [comment]
About 2.

With a qualifier it would look like:

```
@ApplicationScoped
@Connector(Kafka.class)
public class KafkaMessagingProvider implements IncomingConnectorFactory, OutgoingConnectorFactory {
```

meaning that when the implementation search for a specific connector implementation, it can use:

```
@Inject
Instance<IncomingConnectorFactory> incomingFactories;

// ...
incomingFactories.select(new ConnectorLiteral(theType).get();
```

**Comment by cescoffier** [comment]
(2) has been addressed in the PR #22.

**Comment by cescoffier** [comment]
Just to summarize the current state:

* the `type` attribute from the config will be renamed to `connector` or `provider`
* the `MessagingProvider` marker interface is going to disappear
* the connector has a name, preferably fully qualified. It does not need to match a class name (opaque string). Example: `io.smallrye.kafka`.
* the connector implementation (bean) use the `@Connector` qualifier indicating the connector name. 
* The `provider` attribute from the `@Incoming` and `@Outgoing` annotation are deleted
* The configuration received by the connectors contain entries following this pattern:
`mp.messaging.[connector-name, ex:io.smallrye.kafka].attr=value`

@hutchig Did I forget anything?

**Comment by hutchig** [comment]
No, I am happy now.
I think the type attribute should be 'connector' and it should match the Qualifier (allowing the same string to be used for any set of Connector classes that use the same qualifier even a pair of incoming outgoing that have the same qualifiers but of course different types.
The connector qualifier (same entity as the qualifier) can be fully qualified for production but, if desired simple for demos etc "Kafka" even.
I like the fact that we said that there were two types of channels, internal and connector channels. Internal ones just have `@Incoming` or `@Outgoing` but connector channels have `@Connector(type)`
I like very much that we use the standard mechanism of CDI to do the binding to connector
implementations.

**Comment by hutchig** [comment]
These concerns are now dealt with.
