### ISSUE TITLE
Context detached streams

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-messaging#3]
Migrated from https://github.com/eclipse/microprofile-reactive-streams/issues/26.

Currently the messaging spec specifies streams that are attached to the lifecycle of the context in which they run - so they are automatically started when the context is started, and automatically shut down when the context is destroyed, and kept running (restarted in case of failure) in the meantime. These streams are provided by declaring an annotated method.

There are also use cases that would require streams detached from a particular context, such as the ability to publish a single event in response to a HTTP request, as well as the ability plumb a WebSocket stream into a message broker. These streams would be provided by declaring @Inject annotated stream types (eg, PublisherBuilder and SubscriberBuilder), and maybe also messaging specific equivalents that offer more functionality, and the container would inject these into beans so that they can be started/stopped by the developer on demand.

**Comment by hutchig** [comment]
Only loosely related to context but perhaps talking about the Emitter class of 'producer' also mentioned in https://github.com/eclipse/microprofile-reactive-messaging/issues/70#issue-494686039 #70

**Comment by cescoffier** [comment]
Yes and No,

Detached streams had the idea of not being managed by the framework. Emitters are still managed.

**Comment by Emily-Jiang** [comment]
In SmallRye, this is implemented via `@Inject @Channel("prices") Publisher publisher`
