### ISSUE TITLE
Metrics support

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-reactive-messaging#31]
I think it would make sense to automatically generate metrics so that the user can see how the application is working and performing.

Primarily, I think it would be helpful to have a counter of the number of messages sent and acknowledged for each channel.

Something like
```
mp.messaging.sent{channel=$channelName} = $numberSent
mp.messaging.acknowledged{channel=$channelName} = $numberAcked
```

**Comment by cescoffier** [comment]
+1

I believe that each connector would also publish some metrics.

**Comment by hutchig** [comment]
Now would be a good time to give this some cycles @Azquelt - one of the best things about FaultTolerence is the work you and others did for built in metrics IMHO.

**Comment by Azquelt** [comment]
Here are some metrics I think would make sense, along with some thoughts and caveats.

1. Counter of messages sent through a channel

Monotonic counters in MP Metrics are more powerful than they first appear since they are sampled regularly so you can compute things like rate of change and moving averages.

This would allow users to see
* the rate of messages passing through the system
* the number of messages currently being processed in a simple flow (by subtracting the count of one channel from the count of another)

This is possible given the current API

2. Counter of messages acknowledged on a channel

This would allow users to see how much work could potentially be repeated if a consumer was to crash (by subtracting the number acknowledged from the number sent).

This is not possible given the current API because there is no way for the implementation to add an acknowledgement callback to a user-created `Message`.

3. Counter of demand by a subscriber to a channel

This would potentially allow the user to see where bottlenecks are occurring in the system by comparing the number of messages demanded with the number actually sent. The numbers retrieved here might be slightly awkward to interpret because some subscribers may demand more messages at a time than others.

I think this is possible given the current API

4. Histogram of time spent for a message to travel from an incoming connector to an outgoing connector

This would allow the user to see the total lag time for messages being processed by the system.

This is not possible because we don't currently have any way to attach a correlation ID to a message as it travels through the system.

As an alternative, we could enable a histogram of the time taken between a message being sent and being acknowledged which might be a better measurement anyway.

With the current API, this metric can only be implemented by the incoming connector because there's no way for the implementation to add an acknowledgement callback to the `Message` created by the incoming connector.

**Comment by Azquelt** [comment]
I'm also unsure whether metrics attached to a channel should be named

* `mp.messaging.somemetric.channelname`
* `mp.messaging.somemetric{channel=channelname}`

The second metric name is conceptually nicer, but prometheus docs suggest only using labels where it makes sense to aggregate the metrics. I'm not sure that it will make sense to aggregate metrics from multiple channels.

**Comment by Azquelt** [comment]
It was mentioned at some point that a counter of demand isn't practical because it's valid according to the spec to repeatedly demand `MAX_LONG` to indicate that there's no limit to the number of messages which can be processed.
