### ISSUE TITLE
Do we want to remove the '.incoming' and '.outgoing' strings from config properties?

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-reactive-messaging#35]
The idea came up in one of the calls that in many cases the
'incoming' and 'outgoing' substring in the properties is redundant.

I do not agree with this myself as I think readers and writers
may want to have different properties and sometimes property
sources exist that are shared.

Also, it may be that a whole 'cloud config server' holds some configuration
properties for both ends of an inter-process connection 
(i.e. more than one microservice) and having the same
name for this channel in both processes is good for clarity but
binding both sides to the same propeties is not 'good'.

A subsequent idea was that 'incoming' or 'outgoing' were optional
but then we would need to spec that these were invalid channel names
(just as 'connector' is!).

Thoughts?

**Comment by cescoffier** [comment]
There are a few things to be discussed:

1. I agree that we should remove them from the key names, so `mp.messaging.incoming.foo` would become `mp.messaging.foo`. 
2. To have 1. we must guarantee that channel names are unique, I actually in favor of this, and I'm pretty sure I'm making this assumption already (`Map<String, ...>` with the key being the channel name)
3. But the weaving of the different elements (methods and connectors) would require to know the _direction_ of the channel (inbound or outbound). So, we would need to add a `.direction` attribute=`inbound|outbound` (or `incoming|outgoing`).

**Comment by cescoffier** [comment]
After discussion, we decided to keep them because:

1. it makes the configuration mode understandable
2. it does not reduce the readability too much
