### ISSUE TITLE
How many outstanding acknowledgements should be permitted?

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-reactive-messaging#38]
After `Message.ack()` is called, a `CompletionStage` is returned which is completed when the acknowledgement has been processed.

Should an implementation wait for this to happen before accepting the next message or not?

Currently, the smallrye implementation will wait for the acknowledgement to complete (as if it's using `ReactiveStreams.flatMapCompletionStage()`).

If Kafka is the source system, then the desired behaviour is *not* to wait so that many messages can be acknowledged and then batched up into one commit. (Doing basic testing on my laptop, I found that batching commits resulted in an 80x increase in throughput vs. committing every message individually)

**Comment by cescoffier** [comment]
This is something that needs to be handled by the connector.

**Comment by hutchig** [comment]
Discussed in hangout, javadoc appears ok.
Andrew will follow up with a smallrye issue to make sure that impl matches the current javadoc.
Agreed to close.

**Comment by Azquelt** [comment]
The Javadoc on `@Outgoing` explains what's meant to happen:
> Containers may provide the ability to configure batching of acks, or only acking one in every `n` messages.

So the container may provide an option to allow batching of acknowledgements.
