### ISSUE TITLE
Acknowledgement Examples seems inconsistent

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-reactive-messaging#49]
The Acknowledgement Examples section says
> The contract for acknowledging messages is anything that accepts a Message is required to acknowledge it.

This seems add odds with the Message Acknowledgement section which allows acknowledgement strategies of:
* `NONE` - meaning that no acknowledgement is done at all
* `PRE_PROCESSING` - meaning that the message is acknowledged before the user's code receives it

This raises a few questions to me:
1) Is it valid to write an application where messages are never acknowledged?
1b) does this have implications for connection authors? (e.g. if you store something for each acknowledgement that you're waiting for, that will cause a memory leak)
2) Should that section in Acknowledgement Examples only apply to message processors where the acknowledgement strategy is `MANUAL`?
3) What's the difference between `NONE` and `MANUAL` for a message processing method which accepts a message object rather than a payload? In both cases it would seem like the framework does nothing?

**Comment by cescoffier** [comment]
> Is it valid to write an application where messages are never acknowledged?
Yes, there are protocols where acknowledgment does not exist (MQTT) or message-based interaction where acknowledgment would not make sense. 

> 1b) does this have implications for connection authors? (e.g. if you store something for each acknowledgment that you're waiting for, that will cause a memory leak)

Fortunately, the connector should be aware whether or not acknowledgment is a _thing_ in the protocol it is dealing with. So should be fine.

That being said, if the protocol requires acknowledgment BUT the user does not acknowledge, that's an application error. 

> Should that section in Acknowledgement Examples only apply to message processors where the acknowledgment strategy is MANUAL?

No strong opinion. Either we switch to manual or we give an example of all the strategies. WDYT?

> What's the difference between NONE and MANUAL for a message processing method which accepts a message object rather than a payload? In both cases, it would seem like the framework does nothing?

In both cases the framework does nothing. However, `NONE` is there to indicate that it is expected that the method does not do acknowledgment. If you use `MANUAL` but you realized that the method does not manage acknowledgment, it's a bug. So it's more a hint for the developer. 

When we came up with the strategies, I was wondering about `NONE` and whether we should just drop it. However, in this case, you would need to use `MANUAL` and that would be odd to use `MANUAL` and to explicitly not calling `ack()` (of course you can use a comment to explain the reasons). 

The opposite was also feeling a bit weird. You would use `NONE` and the method would manage the acknowledgment, so it's not really `NONE`.

**Comment by cescoffier** [comment]
Will update the spec.
