### ISSUE TITLE
How do we tell Connectors about config state such as `@Acknowledgement(None)`

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-reactive-messaging#63]
It would be useful to tell a Connector what the annotations for a method are.

Some specs have a way of overriding Annotations using Config properties and there
is a bit of precedance in the mapping.
e.g.
https://github.com/eclipse/microprofile/pull/100/files
`<fully qualified class name>/<field name>/<spec-defined annotation name>/<annotation attribute name>`.

Could we run this in reverse to arrive at a property that descibes the annotations
that could be passed to the connector.

Just an idea.

**Comment by cescoffier** [comment]
This had been discussed during the hangout. 

`None` was designed for the broadcast use case (where the message si dispatches to several consumer, and you may end up in a situation where only one must acknowledge the message). 

However, this must be clarified in the spec:

* All messages must be acknowledged at least once
* `None` should only be used in the situation where the message is going to be acknowledged somewhere else.
