### ISSUE TITLE
OSGi problems importing the o.e.m.reactive.streams package

### ISSUE THREAD

**Issue by acoburn** [eclipse/microprofile-reactive-messaging#69]
The `microprofile-reactive-messaging` bundle [imports](https://github.com/eclipse/microprofile-reactive-messaging/blob/master/api/bnd.bnd#L5) the `org.eclipse.microprofile.reactive.streams` package, but there is no bundle that exports that package.

For example, the `microprofile-reactive-streams-operators-api` dependency exports these packages:

```
org.eclipse.microprofile.reactive.streams.operators
org.eclipse.microprofile.reactive.streams.operators.spi
```

Perhaps one of those packages was meant in the BND configuration? Or perhaps that import in the BND configuration should simply be removed? At present, it is rather difficult to deploy the `microprofile-reactive-messaging` bundle in an OSGi runtime.

**Comment by cescoffier** [comment]
I believe it's more an issue in `microprofile-reactive-streams-operators-api` which should export `org.eclipse.microprofile.reactive.streams`.

@hutchig @Azquelt how did you work around the issue as you are using OSGi based platforms.

**Comment by hutchig** [comment]
In OpenLiberty we have this bnd file for our bundle:
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.org.eclipse.microprofile.reactive.messaging.1.0/bnd.bnd
Which has:
Import-Package: \
  *
and then uses:
-buildpath: \
...
        com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0;version=latest,\

We also have a rebundled RSO at 
https://github.com/OpenLiberty/open-liberty/blob/integration
/dev/com.ibm.websphere.org.eclipse.microprofile.reactive.streams.operators.1.0/bnd.bnd
which as:
Export-Package: \
  org.eclipse.microprofile.reactive.streams.operators;version=1.0, \
  org.eclipse.microprofile.reactive.streams.operators.core;version=1.0, \
  org.eclipse.microprofile.reactive.streams.operators.spi;version=1.0

I can remember that "operators" was added in after the initial project was
up and running.
I think the only thing that mentions that package now (ie. no ".operators" suffix)
is the package-info.java at https://github.com/eclipse/microprofile-reactive-streams-operators/blob/master/api/src/main/java/org/eclipse/microprofile/reactive/streams/operators/package-info.java
and that is an oversite. 
So @cescoffier I think is the import which should change to have the ".operators"
suffix in all cases?

**Comment by cescoffier** [comment]
@hutchig I believe `https://github.com/eclipse/microprofile-reactive-messaging/blob/master/api/bnd.bnd#L5` need to be updated. Is that what you mean?
