### ISSUE TITLE
Messaging config

### ISSUE THREAD

**Issue by jroper** [eclipse/microprofile-reactive-messaging#7]
Migrated from https://github.com/eclipse/microprofile-reactive-streams/issues/43.

We need to define an approach for configuring messaging.

I'm not sure if there are any generic configuration parameters that we want to support at this stage (though perhaps being able to supply the topic name in configuration instead of in the annotation would be good), but the important thing is that we have a consistent approach for configuring things.

In some prior discussions, we've discussed adding a configuration key attribute to the annotations. The actual name of it is certainly up for debate, `configKey`, `configId`, `streamId`, `id`, `key`, `config` etc are all examples.

The idea would be that if you said:

```java
@Incoming(topic = "mystream", configKey = "com.example.my-stream")
public CompletionStage<?> handleEvent(MyStreamEvent event) {
    ...
}
```

Then configuration for this stream would first be read from the `com.example.my-stream` namespace, before reading it from a general location. So for example, let's say we had a configuration parameter called `parallelism`, in the above case, we'd first read `com.example.my-stream.parallelism`, if not set there, then we might read `org.eclipse.microprofile.reactive.messaging.parallelism`, before finally defaulting to something else. We could also say that you can override the topic defined on the annotation by setting `com.example.my-stream.topic` in the configuration.

Comment by @cescoffier:
I've open an issue related to this (#8), where I propose to remove `topic` and to use a `name`. This name can be used to read the configuration as a default. But this does not avoid adding the `configKey` attribute to let the user configure the configuration key.

Because of MP Config, the configuration is going to be given as:

```
com.example.my-stream.broker=...
com.example.my-stream.consumer-group=...
```

**Comment by cescoffier** [comment]
So there are three "topics":

1. What would be the config key attribute name
2. is the `@Incoming` and `@Outgoing` `name` attribute a valid config key?
3. If (2) is yes, what would be the fully qualified name? Just the `name` attribute, something prefixed with `org.eclipse.microprofile.reactive`?

About 1.

IMHO, `configKey`  seems to fit. It's clear enough, and reduce the usage of this attribute to only the config. This latter point can be seen as a counter-argument. 

About 2 and 3

I believe that `name` can be used as `configKey`. The configuration would be read from the `configKey` if set, and then from the `name`. I don't think it should be prefixed as the user can decide to use a qualified name too. 

It's important to notice that the name does not indicate the (Kafka / AMQP, RabbitMQ...) topic name as this name could be configured in the configuration

**Comment by hutchig** [comment]
It would seem to me that one simple way of abstracting the source of configuration properties
is that the MicroProfile config specification (if present on the class path) is used to source them.

There is a precedent for taking properties (aka MicroProfile Config properties) as additional configuration for annotation in the Fault Tolerance Spec. Those tend to be very located in a user's class-method so have a name space related to that but it would make sense for us to 'fit in' with
the look and feel of that if possible.

For example they use:
   mp.fault.tolerance.interceptor.priority.
so for values that are not related to a specific topic/method that would suggest
  mp.reactive.messaging.xxxx.yyyy

For values that are related to a specific place in the code, they use the convention
(from section 12.1 of the spec):

"Override individual parameters The annotation parameters can be overwritten via config
properties in the naming convention of <classname>/<methodname>/<annotation>/<parameter>."

**Comment by hutchig** [comment]
If the idea of a user settable config namespace prefix, as "configKey" for example sticks, we should raise it as a feature/issue in the fault tolerance spec - indeed for all MP specs it is best for them to have a similar 'style' we should create a cross specification config 'patterns' doc somewhere that gives a common look and feel across multiple specs. The patterns above from FT can apply to any annotation overrides/supplementation.

There is a cross spec group that meets sometimes - so I will go and have a look to see if I can find
some cross spec material/approach.

**Comment by cescoffier** [comment]
Configuration format has been discussed and the spec updated.
