### ISSUE TITLE
producing an event message on every new REST request

### ISSUE THREAD

**Issue by haraldatbmw** [eclipse/microprofile-reactive-messaging#70]
For me it's not clear how a microservice can produce a new message into an outgoing channel triggered on each call of a RESTfull HTTP GET request of this microservice. 

**My Idea**
- All user-facing communication is synchronous via HTTP REST
- Each HTTP REST request produces a new event message
- All service to service communication is event driven using microprofile reactive messaging, proceeding the events initial created by the REST resouces.

What is the answer of the microprofile reactive messaging specification on this kind of problem?

Using SmallRye's proprietary extension for Emitter I can solve this problem. 
But I want to solve it in a "standard spec" way.

```java
@Path("/bookings")
@ApplicationScoped
public class BookingsResource {

    private Random random = new Random();

    @Inject
    @Stream("booking-created")
    Emitter<KafkaMessage<Long, String>> producer;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String createBooking() {
        producer.send(KafkaMessage.of(random.nextLong(), "new booking"));

        return "event produced";
    }
}
```

**Comment by haraldatbmw** [comment]
I found an other way of implementing such a REST resource to reactive streams bridge without using the proprietary extension of SmallRye.

But I'm still not sure if this is the best way to combine these two worlds (REST resources and reactive streams). So I'm very interested in the opinion of the MicroProfile team.

```java
@Path("/bookings")
@ApplicationScoped
public class BookingResource {

    private Random random = new Random();

    private FlowableEmitter<KafkaMessage<Long, String>> emitter;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String createBooking() {
        emitter.onNext(KafkaMessage.of(random.nextLong(), "new booking"));
        return "event produced";
    }

    @Outgoing("booking-created")
    public Publisher<KafkaMessage<Long, String>> produceEvents() {
        return Flowable.<KafkaMessage<Long, String>>create(
            e -> this.emitter = e, 
            BackpressureStrategy.BUFFER);
    }
}
```

**Comment by cescoffier** [comment]
The issue with your approach is that the stream you create it not connected to the streams managed by reactive messaging. However, it's mostly how the emitters are implemented.

**Comment by haraldatbmw** [comment]
> The issue with your approach is that the stream you create it not connected to the streams managed by reactive messaging. However, it's mostly how the emitters are implemented.

I thought the stream is connected via the `@Outgoing("booking-created")` annotation, isn't it?
My second example is working with quarkus/smallrye environment.

**Comment by Emily-Jiang** [comment]
I think this is a good use case. Let's make this into the Reactive Messaging Spec.

**Comment by Legion2** [comment]
Using the implementation of SmallRye it's currently possible to use the experimental feature `@Channel` annotation to get the emitter injected into a bean:
```java
@Inject
@Channel("some-channel")
private Emitter<Data> channel;
...
channel.send(new Data());
```

I hope to see this in the Microprofile Reactive Messaging Spec, because this is very imported for the interoperability of connection based request processing (like REST or WebSockets) and reactive messaging systems.

As reference see smallrye/smallrye-reactive-messaging#284

**Comment by cescoffier** [comment]
We are currently working on the integration in the spec.

**Comment by Emily-Jiang** [comment]
A PR will appear in the next few days...
