### ISSUE TITLE
Tck SubscriberShapeTest outside of spec

### ISSUE THREAD

**Issue by danielkec** [eclipse/microprofile-reactive-messaging#79]
Signature of method [SubscriberBean#consumePayloadsAndReturnSomething](https://github.com/eclipse/microprofile-reactive-messaging/blob/a89bdc57f917827deba171bbea1b067a4aa8c171/tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/subscribers/SubscriberBean.java#L129) is outside of spec defined variants.
```java
    @Incoming("string-payload")
    public String consumePayloadsAndReturnSomething(String payload) {
        increment("string-payload");
        add("string-payload", payload);
        return payload;
    }

```
Spec states:
`Implementations must validate that the stream shape matches the @Outgoing and
@Incoming annotations, if they don’t, a CDI definition exception should be raised to the CDI container
during initialization.`

**Comment by cescoffier** [comment]
That's a good catch @danielkec. 

there are 2 ways to handle this issue:

1. we can add the signature to the spec, explaining that the result is discarded.
2. explicitly drop this signature

WDYT?

**Comment by danielkec** [comment]
I would prefer fixing TCK, spec advice to discourage users from calling msg. methods directly. Optional return type kind of encourage users for reusing msg. methods for direct calls.

**Comment by cescoffier** [comment]
We discussed this issue during the MicroProfile Reactive call, and we are going to:

* Add tests verifying that this signature is not allowed
* Drop the current test
* Fix the spec as it is rather ambiguous
