### ISSUE TITLE
Bad method signature in spec

### ISSUE THREAD

**Issue by danielkec** [eclipse/microprofile-reactive-messaging#81]
Incoming method signatures is the spec:
```java
@Incoming("channel") 
SubscriberBuilder<Message<I>> method()
```
and
```java
@Incoming("channel")
SubscriberBuilder<I> method()
```
But SubscriberBuilder has two generic params:
```java
 * @param <T> The type of the elements that this subscriber consumes.
 * @param <R> The type of the result that this subscriber emits.
 * @see ReactiveStreams
 */
public interface SubscriberBuilder<T, R> extends ProducesResult<R> {
```
Also the package in the spec:
`org.eclipse.microprofile.reactive.streams.SubscriberBuilder`
doesn't reflect package renaming in the commit https://github.com/eclipse/microprofile-reactive-streams-operators/commit/9e1f1dad81ce170869ffe24fb10665ba755bb7f3#diff-4f2777db82004633f9d0511939f62dc6

**Comment by cescoffier** [comment]
Thanks for the report @danielkec. I've fixed it in master.
