### ISSUE TITLE
MetricsTestBean issues

### ISSUE THREAD

**Issue by cescoffier** [eclipse/microprofile-reactive-messaging#91]
The `MetricsTestBean` class has a few issues:

* There is a `System.out` statement in the `simpleMapping` test
* `inAppMessagesReceived` should be an `AtomicInteger` instead of `volatile`. The `++` operation is not atomic.

**Comment by Azquelt** [comment]
Shall I work on a fix for this?

**Comment by cescoffier** [comment]
If you have some time, that would be great! I discovered the issue while reviewing #87.
