### ISSUE TITLE
How to know available attributes for a connector/channel

### ISSUE THREAD

**Issue by angelozerr** [eclipse/microprofile-reactive-messaging#94]
To provide a better support for tooling, see related issue 
https://github.com/redhat-developer/vscode-quarkus/issues/218#issuecomment-592032968

I mean provide completion, diagnostics, etc for available properties like:

```
# Configure the Kafka sink (we write to it)
mp.messaging.outgoing.generated-price.connector=smallrye-kafka
mp.messaging.outgoing.generated-price.topic=prices
```

I need to know that `smallrye-kafka` connector provides `topic`, `retry` attributes. 

It seems those attributes are hard coded https://github.com/smallrye/smallrye-reactive-messaging/blob/b91e05a0df00bc0cfd302184d4c5663eac2c342b/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/impl/KafkaSource.java#L114

I told me if you could provide a mean to know which attributes are available for a given channel, connector.

An idea is to declare those attributes in the Connector annotation like this:

```java
@Connector("smallrye-kafka", attributes=["topic", "retry", "..."])
public class KafkaConnector implements IncomingConnectorFactory, OutgoingConnectorFactory {

...
}
```

You could use those attributes to manage validation in your side (and generate docs too). In toolings side, it will be easy to collect attributes from a given channel/connector.  

What do you think about this idea?

**Comment by cescoffier** [comment]
I like this idea! 

Unfortunately, `@Connector` comes from the spec, so extending it is not that simple. However, we could introduce a SmallRye annotation like:

```
@Connector("smallrye-kafka")
@ConnectorAttribute(direction="outgoing", name="topic", description="The consumed Kafka topic", 
type=String.class)
@ConnectorAttribute(direction="outgoing", name="retry", description="The number of attempted retry to connecto to the Kafka broker", type=Long.TYPE)
```

@kenfinnigan WDYT?

**Comment by kenfinnigan** [comment]
I think it makes sense to have a separate annotation.

`@ConnectorAttribute` is one option, `@ConnectorDefinition` is another

**Comment by cescoffier** [comment]
The spec uses the term `attribute`.

**Comment by kenfinnigan** [comment]
Just realized this is a spec issue, do we want this in SmallRye first?

**Comment by cescoffier** [comment]
Well, the approach must be validated in SmallRye (or any other implementation) first.

**Comment by angelozerr** [comment]
> I like this idea!

Great! Glad you like the idea.

> @ConnectorAttribute is one option, @ConnectorDefinition is another

Have you some idea about those annotation name, package and attributes? If yes, could you just me a basic sample about those future annotation? I would like to start supporting `microprofile-reactive-messaging` in vscode-quakus. If I know about those annotation, it will help me a lot. Thanks!

**Comment by cescoffier** [comment]
@angelozerr Here is it the version we are experimenting in SmallRye:
https://github.com/smallrye/smallrye-reactive-messaging/pull/456/files#diff-d8a31865502e6928761775e3eb5aa222

**Comment by angelozerr** [comment]
> @angelozerr Here is it the version we are experimenting in SmallRye:
https://github.com/smallrye/smallrye-reactive-messaging/pull/456/files#diff-d8a31865502e6928761775e3eb5aa222

Thanks @cescoffier for this info!

Do you know when this annotation could be available? I would like just to know if I could start to work on this feature now or if I must wait for several weeks?

**Comment by kenfinnigan** [comment]
Depends on what you mean.

It will be available in a SmallRye Reactive Messaging release within the next week I suspect.

If you're referring to the specification, it would likely be at least 6 months before we propose the addition to the specification as we need to ensure that what we've developed in the project is appropriate or needs adjustments first.

**Comment by angelozerr** [comment]
> Depends on what you mean.

I mean providing this annotation and using this annotation is some messages like kafka, in order to start providing a good tooling support for Reactive Messaging.

**Comment by kenfinnigan** [comment]
As I mentioned, for the SmallRye implementation it will be available soon.

For the Specification, that will be further down the road, possibly 6 mths or more

**Comment by angelozerr** [comment]
Thanks @kenfinnigan for your clarification.

**Comment by cescoffier** [comment]
SmallRye implementation:

* https://github.com/smallrye/smallrye-reactive-messaging/blob/master/api/src/main/java/io/smallrye/reactive/messaging/annotations/ConnectorAttribute.java
* https://github.com/smallrye/smallrye-reactive-messaging/blob/master/api/src/main/java/io/smallrye/reactive/messaging/annotations/ConnectorAttributes.java

**Comment by angelozerr** [comment]
Thanks @cescoffier, it's great. I will start implementing reactive-messaging support in 2 weeks and I will give you some feedback if it misses something and to know if you will like the support that I have in my mind.

IMHO I think those 2 annotations should belong to reactive-messaging API, because all reractive-messaging implementation could benefit with our IDE/Editor support (IJ, vscode, Eclipse, etc). Do you think it's a good idea? If you like this idea could you propose this idea to reactive-messaging API when our IDE/Editor support will be implemented.

**Comment by Emily-Jiang** [comment]
@angelozerr We will add the annotation in the MicroProfile Reactive Messaging spec so that the backend of MP LSP can rely on this as you said. In today's MP RM hangout with Clement, we agreed that we will port the changes from the link provided by @cescoffier.

**Comment by angelozerr** [comment]
> @angelozerr We will add the annotation in the MicroProfile Reactive Messaging spec so that the backend of MP LSP can rely on this as you said.

Thanks @Emily-Jiang for your clarification, but I think if those annotation will move to MicroProfile Reactive Messaging API, their package name (which use `io.smallrye`) will change no? In other words I wonder if it could be possible to rename the package name ofthose annotations with `org.eclipse.microprofile.reactive.messaging`

**Comment by angelozerr** [comment]
I'm working on this support, here a demo:

![MPReactiveMessagingDemo](https://user-images.githubusercontent.com/1932211/89433494-ad16fe00-d742-11ea-84ef-555c8d22d888.gif)

Any idea, feedback are welcome!

**Comment by cescoffier** [comment]
One word: awesome!
