### ISSUE TITLE
Add support for reporting message processing failure, as well as acknowledgement

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-reactive-messaging#98]
Currently, the spec has support for a message being acknowledged (indicating that processing has completed successfully) but nothing to indicate that processing of a message failed.

This is highlighted by the proposed `Emitter` API in #87. `Emitter.send(T)` returns a `CompletionStage<Void>` which completes when the message is acknowledged, but because it's a `CompletionStage`, you would expect it to complete exceptionally if message processing fails.

Adding message failure reporting might also open up new possibilities for better ways of handling processing failures. At the moment, the only option is to send a failure signal downstream, causing the stream to terminate (unless the user adds some kind of recovery, but the RM spec doesn't include any tools for doing that.) If message failure reporting were available, it might make more sense to propagate the failure back to the source of the message, allowing the source retry processing (by sending the same message again) or take some other recovery action (such as sending the message to a dead letter queue).

**Comment by cescoffier** [comment]
SmallRye implements a Message'nack: https://github.com/smallrye/smallrye-reactive-messaging/blob/master/api/src/main/java/org/eclipse/microprofile/reactive/messaging/Message.java#L459

(https://github.com/smallrye/smallrye-reactive-messaging/blob/master/api/src/test/java/org/eclipse/microprofile/reactive/messaging/AckNackChainTest.java)

**Comment by pilhuhn** [comment]
Not sure if I completely understood the original issue. 
I'd also expect to `completeExceptionally` if e.g. the underlying sender can't send the message/payload *before* even hitting e.g. Kafka, the exception should also bubble up.

My use case is to do Schema enforcement so that if the sender's message does not conform ot the schema, it will be caught way before the message hits Kafka.
